// Code generated by goctl. DO NOT EDIT.
package types

type VerifyTokenReq struct {
}

type VerifyTokenResp struct {
	UserId int64 `json:"userId"`
	Ok     bool  `json:"ok"`
}

type VerifyPingResp struct {
	Ok string `json:"ok"`
}

type VerifyLoginReq struct {
	Username string `json:"username"`
	Pass     string `json:"username"`
}

type VerifyLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
