// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateTokenReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenReq) Reset()         { *m = GenerateTokenReq{} }
func (m *GenerateTokenReq) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenReq) ProtoMessage()    {}
func (*GenerateTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{0}
}

func (m *GenerateTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenReq.Unmarshal(m, b)
}
func (m *GenerateTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenReq.Marshal(b, m, deterministic)
}
func (m *GenerateTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenReq.Merge(m, src)
}
func (m *GenerateTokenReq) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenReq.Size(m)
}
func (m *GenerateTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenReq proto.InternalMessageInfo

func (m *GenerateTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GenerateTokenResp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessExpire         int64    `protobuf:"varint,2,opt,name=accessExpire,proto3" json:"accessExpire,omitempty"`
	RefreshAfter         int64    `protobuf:"varint,3,opt,name=refreshAfter,proto3" json:"refreshAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTokenResp) Reset()         { *m = GenerateTokenResp{} }
func (m *GenerateTokenResp) String() string { return proto.CompactTextString(m) }
func (*GenerateTokenResp) ProtoMessage()    {}
func (*GenerateTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{1}
}

func (m *GenerateTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTokenResp.Unmarshal(m, b)
}
func (m *GenerateTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTokenResp.Marshal(b, m, deterministic)
}
func (m *GenerateTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTokenResp.Merge(m, src)
}
func (m *GenerateTokenResp) XXX_Size() int {
	return xxx_messageInfo_GenerateTokenResp.Size(m)
}
func (m *GenerateTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTokenResp proto.InternalMessageInfo

func (m *GenerateTokenResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GenerateTokenResp) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *GenerateTokenResp) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

type ClearTokenReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearTokenReq) Reset()         { *m = ClearTokenReq{} }
func (m *ClearTokenReq) String() string { return proto.CompactTextString(m) }
func (*ClearTokenReq) ProtoMessage()    {}
func (*ClearTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{2}
}

func (m *ClearTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearTokenReq.Unmarshal(m, b)
}
func (m *ClearTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearTokenReq.Marshal(b, m, deterministic)
}
func (m *ClearTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearTokenReq.Merge(m, src)
}
func (m *ClearTokenReq) XXX_Size() int {
	return xxx_messageInfo_ClearTokenReq.Size(m)
}
func (m *ClearTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClearTokenReq proto.InternalMessageInfo

func (m *ClearTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ClearTokenResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearTokenResp) Reset()         { *m = ClearTokenResp{} }
func (m *ClearTokenResp) String() string { return proto.CompactTextString(m) }
func (*ClearTokenResp) ProtoMessage()    {}
func (*ClearTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{3}
}

func (m *ClearTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearTokenResp.Unmarshal(m, b)
}
func (m *ClearTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearTokenResp.Marshal(b, m, deterministic)
}
func (m *ClearTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearTokenResp.Merge(m, src)
}
func (m *ClearTokenResp) XXX_Size() int {
	return xxx_messageInfo_ClearTokenResp.Size(m)
}
func (m *ClearTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClearTokenResp proto.InternalMessageInfo

func (m *ClearTokenResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ValidateTokenReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenReq) Reset()         { *m = ValidateTokenReq{} }
func (m *ValidateTokenReq) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenReq) ProtoMessage()    {}
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{4}
}

func (m *ValidateTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenReq.Unmarshal(m, b)
}
func (m *ValidateTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenReq.Marshal(b, m, deterministic)
}
func (m *ValidateTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenReq.Merge(m, src)
}
func (m *ValidateTokenReq) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenReq.Size(m)
}
func (m *ValidateTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenReq proto.InternalMessageInfo

func (m *ValidateTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ValidateTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateTokenResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenResp) Reset()         { *m = ValidateTokenResp{} }
func (m *ValidateTokenResp) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResp) ProtoMessage()    {}
func (*ValidateTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{5}
}

func (m *ValidateTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResp.Unmarshal(m, b)
}
func (m *ValidateTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResp.Marshal(b, m, deterministic)
}
func (m *ValidateTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResp.Merge(m, src)
}
func (m *ValidateTokenResp) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResp.Size(m)
}
func (m *ValidateTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResp proto.InternalMessageInfo

func (m *ValidateTokenResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ValidateLoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateLoginReq) Reset()         { *m = ValidateLoginReq{} }
func (m *ValidateLoginReq) String() string { return proto.CompactTextString(m) }
func (*ValidateLoginReq) ProtoMessage()    {}
func (*ValidateLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{6}
}

func (m *ValidateLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateLoginReq.Unmarshal(m, b)
}
func (m *ValidateLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateLoginReq.Marshal(b, m, deterministic)
}
func (m *ValidateLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateLoginReq.Merge(m, src)
}
func (m *ValidateLoginReq) XXX_Size() int {
	return xxx_messageInfo_ValidateLoginReq.Size(m)
}
func (m *ValidateLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateLoginReq proto.InternalMessageInfo

func (m *ValidateLoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ValidateLoginReq) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type ValidateLoginResp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AccessExpire         int64    `protobuf:"varint,2,opt,name=AccessExpire,proto3" json:"AccessExpire,omitempty"`
	RefreshAfter         int64    `protobuf:"varint,3,opt,name=RefreshAfter,proto3" json:"RefreshAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateLoginResp) Reset()         { *m = ValidateLoginResp{} }
func (m *ValidateLoginResp) String() string { return proto.CompactTextString(m) }
func (*ValidateLoginResp) ProtoMessage()    {}
func (*ValidateLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{7}
}

func (m *ValidateLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateLoginResp.Unmarshal(m, b)
}
func (m *ValidateLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateLoginResp.Marshal(b, m, deterministic)
}
func (m *ValidateLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateLoginResp.Merge(m, src)
}
func (m *ValidateLoginResp) XXX_Size() int {
	return xxx_messageInfo_ValidateLoginResp.Size(m)
}
func (m *ValidateLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateLoginResp proto.InternalMessageInfo

func (m *ValidateLoginResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ValidateLoginResp) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *ValidateLoginResp) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

func init() {
	proto.RegisterType((*GenerateTokenReq)(nil), "pb.GenerateTokenReq")
	proto.RegisterType((*GenerateTokenResp)(nil), "pb.GenerateTokenResp")
	proto.RegisterType((*ClearTokenReq)(nil), "pb.ClearTokenReq")
	proto.RegisterType((*ClearTokenResp)(nil), "pb.ClearTokenResp")
	proto.RegisterType((*ValidateTokenReq)(nil), "pb.ValidateTokenReq")
	proto.RegisterType((*ValidateTokenResp)(nil), "pb.ValidateTokenResp")
	proto.RegisterType((*ValidateLoginReq)(nil), "pb.ValidateLoginReq")
	proto.RegisterType((*ValidateLoginResp)(nil), "pb.ValidateLoginResp")
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_61c7956abb761639) }

var fileDescriptor_61c7956abb761639 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0x43, 0xf9, 0x13, 0xde, 0x79, 0x85, 0xc0, 0x04, 0x0d, 0xe1, 0x44, 0xea, 0x41, 0xe3,
	0xa1, 0x26, 0xe2, 0xd1, 0x83, 0xc5, 0x18, 0x63, 0xe2, 0xa9, 0x31, 0x1e, 0xbc, 0xb5, 0x30, 0x60,
	0x03, 0x76, 0xd7, 0xdd, 0xd5, 0xe8, 0xc1, 0x0f, 0xed, 0x37, 0x30, 0xdd, 0x85, 0xba, 0x5d, 0x9a,
	0xe8, 0x8d, 0x79, 0xf2, 0xec, 0x3c, 0xcc, 0x6f, 0xa6, 0xd0, 0x4d, 0xe7, 0x94, 0xa9, 0x54, 0x7d,
	0x04, 0x5c, 0x30, 0xc5, 0xd0, 0xe3, 0x89, 0x7f, 0x02, 0xbd, 0x1b, 0xca, 0x48, 0xc4, 0x8a, 0xee,
	0xd9, 0x8a, 0xb2, 0x88, 0x5e, 0xf0, 0x00, 0x5a, 0xaf, 0x92, 0xc4, 0xed, 0x7c, 0x58, 0x1b, 0xd7,
	0x8e, 0xeb, 0xd1, 0xa6, 0xf2, 0x3f, 0xa1, 0xef, 0x78, 0x25, 0xc7, 0x31, 0xfc, 0x8f, 0x67, 0x33,
	0x92, 0x52, 0x4b, 0xfa, 0xc5, 0xbf, 0xc8, 0x96, 0xd0, 0x87, 0x3d, 0x53, 0x5e, 0xbf, 0xf3, 0x54,
	0xd0, 0xd0, 0xd3, 0x4d, 0x4b, 0x5a, 0xee, 0x11, 0xb4, 0x10, 0x24, 0x9f, 0xc2, 0x85, 0x22, 0x31,
	0xac, 0x1b, 0x8f, 0xad, 0xf9, 0x47, 0xd0, 0xb9, 0x5a, 0x53, 0x2c, 0x7e, 0xfd, 0x9f, 0x63, 0xe8,
	0xda, 0x46, 0xc9, 0xb1, 0x0b, 0x1e, 0x5b, 0x69, 0x57, 0x3b, 0xf2, 0xd8, 0xca, 0xbf, 0x84, 0xde,
	0x43, 0xbc, 0x4e, 0xe7, 0x7f, 0x98, 0x1a, 0x07, 0xd0, 0x54, 0x7a, 0x34, 0x4f, 0x8f, 0x66, 0x0a,
	0xff, 0x10, 0xfa, 0x4e, 0x87, 0x8a, 0x98, 0xe9, 0x4f, 0xcc, 0x1d, 0x5b, 0xa6, 0x3a, 0x66, 0x04,
	0xed, 0xbc, 0x71, 0x16, 0x3f, 0xd3, 0x06, 0x56, 0x51, 0x23, 0x42, 0x83, 0xc7, 0x52, 0x6e, 0x92,
	0xf4, 0xef, 0x1c, 0xba, 0xd3, 0xc3, 0x40, 0x0f, 0x77, 0xa1, 0x87, 0x65, 0xe8, 0x61, 0x05, 0xf4,
	0xd0, 0x81, 0x1e, 0x55, 0x40, 0xb7, 0xb5, 0xb3, 0xaf, 0x1a, 0xb4, 0xb7, 0x67, 0x83, 0x17, 0xd0,
	0x59, 0xda, 0x07, 0x80, 0x83, 0x80, 0x27, 0x81, 0x7b, 0x3f, 0xa3, 0xfd, 0x0a, 0x55, 0x72, 0x9c,
	0x00, 0xcc, 0x8a, 0xb5, 0x60, 0x3f, 0x37, 0x95, 0xf6, 0x39, 0x42, 0x57, 0x92, 0x3c, 0x8f, 0x7c,
	0xb3, 0x39, 0x9b, 0x48, 0x77, 0x79, 0x26, 0x72, 0x77, 0x21, 0xe7, 0xd0, 0xd4, 0xd0, 0xca, 0xaf,
	0xb6, 0xbb, 0x28, 0xbf, 0x2a, 0xe8, 0x4e, 0x5b, 0x8f, 0x8d, 0xe0, 0x94, 0x27, 0x49, 0x4b, 0x7f,
	0x26, 0x93, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0xca, 0x99, 0x9c, 0x38, 0x03, 0x00, 0x00,
}
