// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	verify "ydd_finance/app/identity/api/internal/handler/verify"
	"ydd_finance/app/identity/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/verify/token",
				Handler: verify.TokenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: verify.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: verify.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/identity/v1"),
	)
}
